/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

/**
 *
 * @author Verosffy
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiAdmin = new javax.swing.JMenuItem();
        jmiTeljesValasztek = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmiValogatas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiAkciosAjanlatok = new javax.swing.JMenuItem();
        jmiCsokorOsszeallitasa = new javax.swing.JMenuItem();
        jmiKosarTartalma = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jmiMentettMegrendelesek = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jmiAdmin.setText("admin");
        jmiAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAdminActionPerformed(evt);
            }
        });
        jMenu1.add(jmiAdmin);

        jMenuBar1.add(jMenu1);

        jmiTeljesValasztek.setText("Virágok");

        jMenuItem1.setText("Teljes választék");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmiTeljesValasztek.add(jMenuItem1);

        jmiValogatas.setText("Válogatás");
        jmiValogatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiValogatasActionPerformed(evt);
            }
        });
        jmiTeljesValasztek.add(jmiValogatas);

        jMenuBar1.add(jmiTeljesValasztek);

        jMenu3.setText("Csokor");
        jMenu3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenu3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jmiAkciosAjanlatok.setText("Akciós ajánlatok");
        jmiAkciosAjanlatok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAkciosAjanlatokActionPerformed(evt);
            }
        });
        jMenu3.add(jmiAkciosAjanlatok);

        jmiCsokorOsszeallitasa.setText("Csokor összeállítása");
        jmiCsokorOsszeallitasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCsokorOsszeallitasaActionPerformed(evt);
            }
        });
        jMenu3.add(jmiCsokorOsszeallitasa);

        jMenuBar1.add(jMenu3);

        jmiKosarTartalma.setText("Kosár");
        jmiKosarTartalma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKosarTartalmaActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Kosár tartalma");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jmiKosarTartalma.add(jMenuItem5);

        jmiMentettMegrendelesek.setText("Mentett megrendelések");
        jmiMentettMegrendelesek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMentettMegrendelesekActionPerformed(evt);
            }
        });
        jmiKosarTartalma.add(jmiMentettMegrendelesek);

        jMenuBar1.add(jmiKosarTartalma);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenu3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3AncestorAdded

    private void jmiAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAdminActionPerformed
        new Admin().setVisible(true);
    }//GEN-LAST:event_jmiAdminActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new TeljesValasztek().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmiValogatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiValogatasActionPerformed
        new Valogatas().setVisible(true);
    }//GEN-LAST:event_jmiValogatasActionPerformed

    private void jmiAkciosAjanlatokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAkciosAjanlatokActionPerformed
        new AkciosAjanlatok().setVisible(true);
    }//GEN-LAST:event_jmiAkciosAjanlatokActionPerformed

    private void jmiCsokorOsszeallitasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCsokorOsszeallitasaActionPerformed
        new CsokorOsszeallitasa().setVisible(true);
    }//GEN-LAST:event_jmiCsokorOsszeallitasaActionPerformed

    private void jmiKosarTartalmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKosarTartalmaActionPerformed
        new KosarTartalma().setVisible(true);
    }//GEN-LAST:event_jmiKosarTartalmaActionPerformed

    private void jmiMentettMegrendelesekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMentettMegrendelesekActionPerformed
        new MentettMegerndelesek().setVisible(true);
    }//GEN-LAST:event_jmiMentettMegrendelesekActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new KosarTartalma().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jmiAdmin;
    private javax.swing.JMenuItem jmiAkciosAjanlatok;
    private javax.swing.JMenuItem jmiCsokorOsszeallitasa;
    private javax.swing.JMenu jmiKosarTartalma;
    private javax.swing.JMenuItem jmiMentettMegrendelesek;
    private javax.swing.JMenu jmiTeljesValasztek;
    private javax.swing.JMenuItem jmiValogatas;
    // End of variables declaration//GEN-END:variables
}
